resources:
  - namespaces.yml 
  - website-configmap.yml
  # - ./secrets/sealed-secrets/minio-s3-secret.yml
  # - ./secrets/sealed-secrets/mongo-db-secret.yml
  - ./secrets/minio-s3-secret.yml
  - ./secrets/mongo-db-secret.yml
  - frontend.yml
  - frontend-ingress.yml
  - backend.yml
  - backend-ingress.yml
  - python.yml
  - minio-server.yml
  - minio-ingress.yml
