services:


  minio: 
    image: minio/minio:latest
    container_name: minio
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      - MINIO_ACCESS_KEY=oussachour_minio
      - MINIO_SECRET_KEY=oussachour_minio_pwd
    volumes:
      - minio_data:/data:z
    command: server --console-address ":9090" /data
    networks:
      - qr_network
    env_file:
      - .env
    

  qr_python_code:
    extends: 
      file: docker-compose-A.yml
      service: qr_python_code
    volumes:
      - minio_data:/usr/src/generated_qr:z 
   

  qr_backend: 
    extends: 
      file: docker-compose-A.yml
      service: qr_backend

    

  qr_front:
    extends: 
      file: docker-compose-A.yml
      service: qr_front
    volumes:
      - minio_data:/qr-frontend/assets/data:ro


networks:
  qr_network:
  
volumes:
  minio_data:
  generated_qr: